language: node_js
matrix:
  fast_finish: true
node_js:
- '8'
branches:
  except:
  - build
env:
  global:
    # GITHUB_TOKEN from ptbrowne, regenerate with travis encrypt GITHUB_TOKEN=yourtoken
    secure: tQ6VjFid+RVRkUewKM4ay+tTTvkA2anFqh8rCbpjYt/Q9iFvHwFeBBTTKOuBBdMfGKBhrLw/iFIWB8tezsnhqhMvdFHmsQfcomW+6m7fmxVyQgFOQKztiUUHsju0E2Suy/f9LE/fOrhoDjqk+NS5TLJbBzEZkSWy669T8hABM1c832qlk/luyWw30Fk47yoqr2prEzWgFWsqPYxhSDurwTQ+mAB1JC9hJB8SO0kW5BX6l73JIUbNJrgJlYfK/Bhhn9PzUB4GVdkHsIqoiFlnskIRYSEr5q8cdUcdgVZ3luKEdFJKp3iP1i31J2C20fFU9MMe1RdlnXn3z6nPiI5t2+PrSiPdpIL/pbA+xZae8tk6if7Z7N+/uZ4FZU8JRtvNQ6fzilzQ1Ehluok+4gHwaFpBlUanJ5yEi/g/4R4bXw0hG6eMJGo3c4wo1wyC9vzEoF2DFoNVGCR5+yYZCSm5VyN6mx7/AK2JOomy4msFYy07fMGb8D5N1crzq/AXto9mhrpkvt4msBziWRaIezillTWb3Df5fMN2CPuu8jkys57ZQw8d4iswc3UmcgDKFcPwgCWD+zB61FQD+im31WweHPLW2auZKG5Jujw0n1KVMqkWupdgmIgk1h/7DI8QuXfsSlD9THoQyZPy00X7jcio7FMRd/1vtnZl+ajxG8IwG8I=
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn build
deploy:
- provider: script
  repo: konnectors/cozy-konnector-sncf
  skip-cleanup: true
  script: yarn deploy
  on:
    branch: master
- provider: script
  repo: konnectors/cozy-konnector-sncf
  skip-cleanup: true
  script: DEPLOY_BRANCH=latest yarn deploy
  on:
    branch: prod
